services:
  zomboid:
    build:
      context: .
    image: project-zomboid-arm64:local
    platform: linux/arm64
    restart: unless-stopped
    stop_grace_period: 2m
    ports:
      - "16261-16269:16261-16269/udp"
    environment:
      ADMIN_PASSWORD: ${SERVICE_PASSWORD_ADMIN}
      PZ_JAVA_MODE: ${PZ_JAVA_MODE:-arm64}
      RAM_GB: ${RAM_GB:-8}
      SERVER_ID: ${SERVER_ID:-servertest}
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - zomboid-server:/opt/zomboid-server
      - zomboid-data:/home/zomboid/Zomboid

volumes:
  zomboid-server:
  zomboid-data:
